
data_setup:
    setup_file: "data_setup.py"
    setup_config:
        batch_size: 256
        max_examples: "all"
        data_dir: "data/multinli_0.9/"
        matched: True
        genres: [ 'government' ]
        drop_confused: True
        lowercase: True
        pretrained_vectors: "data/word_vectors/glove.6B.300d.txt"
        normalize_vectors: True
        
model_setup:
    setup_file: "model_setup_example.py"
    setup_config:
        mlp_sizes: [ 1000, 600, 300, 3 ]
        
trainer_setup:
    setup_file: "trainer_setup.py"
    setup_config:
        adam_alpha: .001
        n_epoch: 50
        